repos:
- repo: https://github.com/pycqa/pylint
  rev: v3.2.6
  hooks:
    - id: pylint
      args: ["--rcfile=.pylintrc","-j","0"]
      additional_dependencies:
        - streamlit>=1.29
        - pandas>=1.5
        - numpy>=1.24
        - openai>=1.30
        - tabulate>=0.9.0
